from __future__ import annotations
import _nimblephysics.collision
import _nimblephysics.dynamics
import _nimblephysics.math
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['BallJointConstraint', 'BoxedLcpConstraintSolver', 'BoxedLcpSolver', 'ConstrainedGroup', 'ConstraintBase', 'ConstraintInfo', 'ConstraintSolver', 'DantzigBoxedLcpSolver', 'JointConstraint', 'JointCoulombFrictionConstraint', 'JointLimitConstraint', 'LcpInputs', 'PgsBoxedLcpSolver', 'PgsBoxedLcpSolverOption', 'WeldJointConstraint']
class BallJointConstraint(JointConstraint):
    @typing.overload
    def __init__(self, body: _nimblephysics.dynamics.BodyNode, jointPos: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, body1: _nimblephysics.dynamics.BodyNode, body2: _nimblephysics.dynamics.BodyNode, jointPos: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
class BoxedLcpConstraintSolver(ConstraintSolver):
    @typing.overload
    def __init__(self, timeStep: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, timeStep: typing.SupportsFloat | typing.SupportsIndex, boxedLcpSolver: BoxedLcpSolver) -> None:
        ...
    def buildLcpInputs(self, arg0: ConstrainedGroup) -> LcpInputs:
        ...
    def getBoxedLcpSolver(self) -> BoxedLcpSolver:
        ...
    def getSecondaryBoxedLcpSolver(self) -> BoxedLcpSolver:
        ...
    def makeHyperAccurateAndVerySlow(self) -> None:
        ...
    def setBoxedLcpSolver(self, lcpSolver: BoxedLcpSolver) -> None:
        ...
    def solveLcp(self, arg0: LcpInputs, arg1: ConstrainedGroup) -> list[float]:
        ...
class BoxedLcpSolver:
    def getType(self) -> str:
        ...
    def solve(self, n: typing.SupportsInt | typing.SupportsIndex, A: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, nub: typing.SupportsInt | typing.SupportsIndex, lo: typing.SupportsFloat | typing.SupportsIndex, hi: typing.SupportsFloat | typing.SupportsIndex, findex: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class ConstrainedGroup:
    def __init__(self) -> None:
        ...
    def getConstraint(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> ConstraintBase:
        ...
    def getNumConstraints(self) -> int:
        ...
class ConstraintBase:
    @staticmethod
    def compressPath(skeleton: _nimblephysics.dynamics.Skeleton) -> _nimblephysics.dynamics.Skeleton:
        ...
    @staticmethod
    def getRootSkeletonOf(skeleton: _nimblephysics.dynamics.Skeleton) -> _nimblephysics.dynamics.Skeleton:
        ...
    def applyImpulse(self, impulse: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def applyUnitImpulse(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def excite(self) -> None:
        ...
    def getDimension(self) -> int:
        ...
    def getInformation(self, info: ConstraintInfo) -> None:
        ...
    def getRootSkeleton(self) -> _nimblephysics.dynamics.Skeleton:
        ...
    def getVelocityChange(self, vel: typing.SupportsFloat | typing.SupportsIndex, withCfm: bool) -> None:
        ...
    def isActive(self) -> bool:
        ...
    def isContactConstraint(self) -> bool:
        ...
    def unexcite(self) -> None:
        ...
    def uniteSkeletons(self) -> None:
        ...
    def update(self) -> None:
        ...
class ConstraintInfo:
    pass
class ConstraintSolver:
    def addConstraint(self, constraint: ConstraintBase) -> None:
        ...
    def addSkeleton(self, skeleton: _nimblephysics.dynamics.Skeleton) -> None:
        ...
    def addSkeletons(self, skeletons: collections.abc.Sequence[_nimblephysics.dynamics.Skeleton]) -> None:
        ...
    def applyConstraintImpulses(self, arg0: collections.abc.Sequence[ConstraintBase], arg1: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def buildConstrainedGroups(self) -> None:
        ...
    def clearLastCollisionResult(self) -> None:
        ...
    def enforceContactAndJointAndCustomConstraintsWithLcp(self) -> None:
        ...
    @typing.overload
    def getCollisionDetector(self) -> _nimblephysics.collision.CollisionDetector:
        ...
    @typing.overload
    def getCollisionDetector(self) -> _nimblephysics.collision.CollisionDetector:
        ...
    @typing.overload
    def getCollisionGroup(self) -> _nimblephysics.collision.CollisionGroup:
        ...
    @typing.overload
    def getCollisionGroup(self) -> _nimblephysics.collision.CollisionGroup:
        ...
    def getConstrainedGroups(self) -> list[ConstrainedGroup]:
        ...
    def getConstraints(self) -> list[ConstraintBase]:
        ...
    def getGradientEnabled(self) -> bool:
        ...
    def getTimeStep(self) -> float:
        ...
    def removeAllConstraints(self) -> None:
        ...
    def removeAllSkeletons(self) -> None:
        ...
    def removeConstraint(self, constraint: ConstraintBase) -> None:
        ...
    def removeSkeleton(self, skeleton: _nimblephysics.dynamics.Skeleton) -> None:
        ...
    def removeSkeletons(self, skeletons: collections.abc.Sequence[_nimblephysics.dynamics.Skeleton]) -> None:
        ...
    def replaceEnforceContactAndJointAndCustomConstraintsFn(self, arg0: collections.abc.Callable[[], None]) -> None:
        ...
    def setCollisionDetector(self, collisionDetector: _nimblephysics.collision.CollisionDetector) -> None:
        ...
    def setContactClippingDepth(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def setGradientEnabled(self, arg0: bool) -> None:
        ...
    def setPenetrationCorrectionEnabled(self, arg0: bool) -> None:
        ...
    def setTimeStep(self, timeStep: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def solve(self) -> None:
        ...
    def solveConstrainedGroups(self) -> None:
        ...
    def updateConstraints(self) -> None:
        ...
class DantzigBoxedLcpSolver(BoxedLcpSolver):
    @staticmethod
    def getStaticType() -> str:
        ...
    def getType(self) -> str:
        ...
    def solve(self, n: typing.SupportsInt | typing.SupportsIndex, A: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, nub: typing.SupportsInt | typing.SupportsIndex, lo: typing.SupportsFloat | typing.SupportsIndex, hi: typing.SupportsFloat | typing.SupportsIndex, findex: typing.SupportsInt | typing.SupportsIndex, earlyTermination: bool) -> bool:
        ...
class JointConstraint(ConstraintBase):
    @staticmethod
    def getConstraintForceMixing() -> float:
        ...
    @staticmethod
    def getErrorAllowance() -> float:
        ...
    @staticmethod
    def getErrorReductionParameter() -> float:
        ...
    @staticmethod
    def getMaxErrorReductionVelocity() -> float:
        ...
    @staticmethod
    def setConstraintForceMixing(cfm: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setErrorAllowance(allowance: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setErrorReductionParameter(erp: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setMaxErrorReductionVelocity(erv: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class JointCoulombFrictionConstraint(ConstraintBase):
    @staticmethod
    def getConstraintForceMixing() -> float:
        ...
    @staticmethod
    def setConstraintForceMixing(cfm: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __init__(self, joint: _nimblephysics.dynamics.Joint) -> None:
        ...
class JointLimitConstraint(ConstraintBase):
    @staticmethod
    def getConstraintForceMixing() -> float:
        ...
    @staticmethod
    def getErrorAllowance() -> float:
        ...
    @staticmethod
    def getErrorReductionParameter() -> float:
        ...
    @staticmethod
    def getMaxErrorReductionVelocity() -> float:
        ...
    @staticmethod
    def setConstraintForceMixing(cfm: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setErrorAllowance(allowance: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setErrorReductionParameter(erp: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def setMaxErrorReductionVelocity(erv: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __init__(self, joint: _nimblephysics.dynamics.Joint) -> None:
        ...
class LcpInputs:
    @property
    def mA(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @mA.setter
    def mA(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
        ...
    @property
    def mB(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @mB.setter
    def mB(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def mFIndex(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @mFIndex.setter
    def mFIndex(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"]) -> None:
        ...
    @property
    def mHi(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @mHi.setter
    def mHi(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def mLo(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @mLo.setter
    def mLo(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def mOffset(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @mOffset.setter
    def mOffset(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"]) -> None:
        ...
    @property
    def mW(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @mW.setter
    def mW(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def mX(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @mX.setter
    def mX(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
class PgsBoxedLcpSolver(BoxedLcpSolver):
    @staticmethod
    def getStaticType() -> str:
        ...
    def getOption(self) -> PgsBoxedLcpSolverOption:
        ...
    def getType(self) -> str:
        ...
    def setOption(self, option: PgsBoxedLcpSolverOption) -> None:
        ...
    def solve(self, n: typing.SupportsInt | typing.SupportsIndex, A: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, nub: typing.SupportsInt | typing.SupportsIndex, lo: typing.SupportsFloat | typing.SupportsIndex, hi: typing.SupportsFloat | typing.SupportsIndex, findex: typing.SupportsInt | typing.SupportsIndex, earlyTermination: bool) -> bool:
        ...
class PgsBoxedLcpSolverOption:
    mRandomizeConstraintOrder: bool
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, maxIteration: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, maxIteration: typing.SupportsInt | typing.SupportsIndex, deltaXTolerance: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, maxIteration: typing.SupportsInt | typing.SupportsIndex, deltaXTolerance: typing.SupportsFloat | typing.SupportsIndex, relativeDeltaXTolerance: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, maxIteration: typing.SupportsInt | typing.SupportsIndex, deltaXTolerance: typing.SupportsFloat | typing.SupportsIndex, relativeDeltaXTolerance: typing.SupportsFloat | typing.SupportsIndex, epsilonForDivision: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, maxIteration: typing.SupportsInt | typing.SupportsIndex, deltaXTolerance: typing.SupportsFloat | typing.SupportsIndex, relativeDeltaXTolerance: typing.SupportsFloat | typing.SupportsIndex, epsilonForDivision: typing.SupportsFloat | typing.SupportsIndex, randomizeConstraintOrder: bool) -> None:
        ...
    @property
    def mDeltaXThreshold(self) -> float:
        ...
    @mDeltaXThreshold.setter
    def mDeltaXThreshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def mEpsilonForDivision(self) -> float:
        ...
    @mEpsilonForDivision.setter
    def mEpsilonForDivision(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def mMaxIteration(self) -> int:
        ...
    @mMaxIteration.setter
    def mMaxIteration(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def mRelativeDeltaXTolerance(self) -> float:
        ...
    @mRelativeDeltaXTolerance.setter
    def mRelativeDeltaXTolerance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class WeldJointConstraint(JointConstraint):
    @typing.overload
    def __init__(self, body: _nimblephysics.dynamics.BodyNode) -> None:
        ...
    @typing.overload
    def __init__(self, body1: _nimblephysics.dynamics.BodyNode, body2: _nimblephysics.dynamics.BodyNode) -> None:
        ...
    def setRelativeTransform(self, tf: _nimblephysics.math.Isometry3) -> None:
        ...
