"""
Bindings for Eigen geometric types.
"""
from __future__ import annotations
import _nimblephysics.dynamics
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['AdR', 'AdT', 'AngleAxis', 'BoundingBox', 'GraphFlowDiscretizer', 'Isometry3', 'MultivariateGaussian', 'ParticlePath', 'PolynomialFitter', 'Quaternion', 'Random', 'RelativeFilter', 'dAdInvT', 'dAdT', 'distancePointToConvexHull2D', 'distancePointToConvexHullProjectedTo2D', 'eulerXYXToMatrix', 'eulerXYZToMatrix', 'eulerXZXToMatrix', 'eulerXZYToMatrix', 'eulerYXYToMatrix', 'eulerYXZToMatrix', 'eulerYZXToMatrix', 'eulerYZYToMatrix', 'eulerZXYToMatrix', 'eulerZXZToMatrix', 'eulerZYXToMatrix', 'eulerZYZToMatrix', 'expAngular', 'expMap', 'expMapJac', 'expMapRot', 'expToQuat', 'leftMultiplyInFreeJointSpace', 'logMap', 'matrixToEulerXYX', 'matrixToEulerXYZ', 'matrixToEulerXZY', 'matrixToEulerYXZ', 'matrixToEulerYZX', 'matrixToEulerZXY', 'matrixToEulerZYX', 'quatToExp', 'rightMultiplyInFreeJointSpace', 'roundEulerAnglesToNearest', 'transformBy', 'verifyRotation', 'verifyTransform']
class AngleAxis:
    """
    Bindings for Eigen::AngleAxis<>.
    """
    @staticmethod
    def Identity() -> AngleAxis:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, angle: typing.SupportsFloat | typing.SupportsIndex, axis: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, quaternion: Quaternion) -> None:
        ...
    @typing.overload
    def __init__(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"]) -> None:
        ...
    @typing.overload
    def __init__(self, other: AngleAxis) -> None:
        ...
    def __str__(self) -> str:
        ...
    def angle(self) -> float:
        ...
    def axis(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def inverse(self) -> AngleAxis:
        ...
    def multiply(self, arg0: AngleAxis) -> Quaternion:
        ...
    def quaternion(self) -> Quaternion:
        ...
    def rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def set_angle(self, angle: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def set_axis(self, axis: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    def set_quaternion(self, arg0: Quaternion) -> None:
        ...
    def set_rotation(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"]) -> None:
        ...
    def to_rotation_matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
class BoundingBox:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, min: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], max: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    def computeCenter(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def computeFullExtents(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def computeHalfExtents(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def getMax(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def getMin(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class GraphFlowDiscretizer:
    def __init__(self, numNodes: typing.SupportsInt | typing.SupportsIndex, arcs: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], nodeAttachedToSink: collections.abc.Sequence[bool]) -> None:
        ...
    def cleanUpArcRates(self, energyLevels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], arcRates: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        """
        This will find the least-squares closest rates of transfer across the arcs to end up with the energy levels at each node we got over time. The idea here is that arc rates may not perfectly reflect the observed changes in energy levels.
        """
    def discretize(self, maxSimultaneousParticles: typing.SupportsInt | typing.SupportsIndex, energyLevels: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], arcRates: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> list[ParticlePath]:
        """
        This will attempt to create a set of ParticlePath objects that map the recorded graph node levels and flows as closely as possible. The particles can be created and destroyed within the arcs.
        """
class Isometry3:
    @staticmethod
    def Identity() -> Isometry3:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, matrix: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]", "flags.f_contiguous"]) -> None:
        ...
    @typing.overload
    def __init__(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"], translation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, quaternion: Quaternion, translation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, other: Isometry3) -> None:
        ...
    def __str__(self) -> str:
        ...
    def inverse(self) -> Isometry3:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @typing.overload
    def multiply(self, other: Isometry3) -> Isometry3:
        ...
    @typing.overload
    def multiply(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def pretranslate(self, other: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    def quaternion(self) -> Quaternion:
        ...
    def rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def set_matrix(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]", "flags.f_contiguous"]) -> None:
        ...
    def set_quaternion(self, arg0: Quaternion) -> None:
        ...
    def set_rotation(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"]) -> None:
        ...
    def set_translation(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    def translate(self, other: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    def translation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class MultivariateGaussian:
    @staticmethod
    def loadFromCSV(file: str, columns: collections.abc.Sequence[str], units: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> MultivariateGaussian:
        ...
    def __init__(self, variables: collections.abc.Sequence[str], mu: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], cov: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
        ...
    def computeLogPDF(self, values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], normalized: bool = True) -> float:
        ...
    def computeLogPDFGrad(self, x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def computePDF(self, values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> float:
        ...
    def condition(self, observedValues: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> MultivariateGaussian:
        ...
    def convertFromMap(self, values: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def convertToMap(self, values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> dict[str, float]:
        ...
    def debugToStdout(self) -> None:
        ...
    def getCov(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getCovSubset(self, rowIndices: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], colIndices: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getLogNormalizationConstant(self) -> float:
        ...
    def getMean(self, variable: str) -> float:
        ...
    def getMu(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getMuSubset(self, indices: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getObservedIndices(self, observedValues: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> list[int]:
        ...
    def getUnobservedIndices(self, observedValues: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> list[int]:
        ...
    def getVariableNameAtIndex(self, i: typing.SupportsInt | typing.SupportsIndex) -> str:
        ...
    def getVariableNames(self) -> list[str]:
        ...
class ParticlePath:
    @property
    def energyValue(self) -> float:
        ...
    @energyValue.setter
    def energyValue(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def nodeHistory(self) -> list[int]:
        ...
    @nodeHistory.setter
    def nodeHistory(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def startTime(self) -> int:
        ...
    @startTime.setter
    def startTime(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class PolynomialFitter:
    def __init__(self, timesteps: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], order: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def calcCoeffs(self, values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def projectPosVelAccAtTime(self, timestep: typing.SupportsFloat | typing.SupportsIndex, pastValues: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class Quaternion:
    """
    Provides a unit quaternion binding of Eigen::Quaternion<>.
    """
    @staticmethod
    def Identity() -> Quaternion:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, wxyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, w: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex, z: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"]) -> None:
        ...
    @typing.overload
    def __init__(self, other: Quaternion) -> None:
        ...
    def __str__(self) -> str:
        ...
    def conjugate(self) -> Quaternion:
        ...
    def inverse(self) -> Quaternion:
        ...
    @typing.overload
    def multiply(self, arg0: Quaternion) -> Quaternion:
        ...
    @typing.overload
    def multiply(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def set_rotation(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"]) -> None:
        ...
    @typing.overload
    def set_wxyz(self, wxyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]) -> None:
        ...
    @typing.overload
    def set_wxyz(self, w: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex, z: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def to_rotation_matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def w(self) -> float:
        ...
    def wxyz(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]:
        ...
    def x(self) -> float:
        ...
    def xyz(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def y(self) -> float:
        ...
    def z(self) -> float:
        ...
class Random:
    @staticmethod
    def getSeed() -> int:
        ...
    @staticmethod
    def setSeed(seed: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @staticmethod
    def uniform(min: typing.SupportsFloat | typing.SupportsIndex, max: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def __init__(self) -> None:
        ...
class RelativeFilter:
    @staticmethod
    def skew_symmetric(v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        """
        Compute the skew-symmetric matrix for a given 3D vector.
        """
    def __init__(self, acc_std: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., gyro_std: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., mag_std: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ...) -> None:
        ...
    def get_H_jacobian(self, R_wp: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], R_wc: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], acc_jc_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], acc_jc_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_jc_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_jc_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        """
        Compute the Jacobian of the measurement function h.
        """
    def get_M_jacobian(self, R_wp: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], R_wc: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], update: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"] = ...) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        """
        Compute the Jacobian of the measurement function for sensor noise.
        """
    def get_R_pc(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        """
        Get the rotation matrix representing the relative rotation between parent and child.
        """
    def get_h(self, R_wp: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], R_wc: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], acc_jc_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], acc_jc_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_jc_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_jc_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], perturbation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"] = ...) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        """
        Compute the measurement function h with optional perturbations.
        """
    def get_q_pc(self) -> Quaternion:
        """
        Get the quaternion representing the relative rotation between parent and child.
        """
    def set_qs(self, q_wp: Quaternion, q_wc: Quaternion) -> None:
        """
        Set the quaternions for parent and child.
        """
    def update(self, gyro_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], gyro_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], acc_jc_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], acc_jc_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], mag_c: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], dt: typing.SupportsFloat | typing.SupportsIndex) -> None:
        """
        Update the filter with new sensor readings and timestep.
        """
    @property
    def Q(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        """
        Covariance matrix for gyro sensor noise.
        """
    @property
    def R(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        """
        Covariance matrix for accelerometer and magnetometer sensor noise.
        """
def AdR(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def AdT(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def dAdInvT(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def dAdT(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def distancePointToConvexHull2D(P: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]]) -> float:
    ...
def distancePointToConvexHullProjectedTo2D(P: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], normal: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ...) -> float:
    ...
def eulerXYXToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerXYZToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerXZXToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerXZYToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerYXYToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerYXZToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerYZXToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerYZYToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerZXYToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerZXZToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerZYXToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def eulerZYZToMatrix(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def expAngular(s: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> Isometry3:
    ...
def expMap(S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> Isometry3:
    ...
def expMapJac(expmap: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def expMapRot(expmap: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def expToQuat(v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> Quaternion:
    ...
def leftMultiplyInFreeJointSpace(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def logMap(S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerXYX(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerXYZ(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerXZY(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerYXZ(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerYZX(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerZXY(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def matrixToEulerZYX(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def quatToExp(q: Quaternion) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def rightMultiplyInFreeJointSpace(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], S: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
    ...
def roundEulerAnglesToNearest(angle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], previousAngle: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], axisOrder: _nimblephysics.dynamics.AxisOrder = ...) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def transformBy(T: Isometry3, p: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
def verifyRotation(R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> bool:
    ...
def verifyTransform(T: Isometry3) -> bool:
    ...
