from __future__ import annotations
import _nimblephysics.collision
import _nimblephysics.constraint
import _nimblephysics.dynamics
import _nimblephysics.neural
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['World']
class World:
    @staticmethod
    def loadFrom(arg0: str) -> World:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, name: str) -> None:
        ...
    def addDofToActionSpace(self, dofIndex: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def addSimpleFrame(self, frame: _nimblephysics.dynamics.SimpleFrame) -> str:
        ...
    def addSkeleton(self, skeleton: _nimblephysics.dynamics.Skeleton) -> str:
        ...
    def bake(self) -> None:
        ...
    @typing.overload
    def checkCollision(self) -> bool:
        ...
    @typing.overload
    def checkCollision(self, option: _nimblephysics.collision.CollisionOption) -> bool:
        ...
    @typing.overload
    def checkCollision(self, option: _nimblephysics.collision.CollisionOption, result: _nimblephysics.collision.CollisionResult) -> bool:
        ...
    def clone(self) -> World:
        ...
    def colorsToJson(self) -> str:
        ...
    def getAction(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getActionJacobian(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getActionSize(self) -> int:
        ...
    def getActionSpace(self) -> list[int]:
        ...
    def getBodyNodeByIndex(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> _nimblephysics.dynamics.BodyNode:
        ...
    def getCachedLCPSolution(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getConstraintSolver(self) -> _nimblephysics.constraint.ConstraintSolver:
        ...
    def getContactClippingDepth(self) -> float:
        ...
    def getControlForceLowerLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getControlForceUpperLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getControlForces(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getCoriolisAndGravityAndExternalForces(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getCoriolisAndGravityForces(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getFallbackConstraintForceMixingConstant(self) -> float:
        ...
    def getGravity(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def getIndex(self, index: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def getInvMassMatrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getLastCollisionResult(self) -> _nimblephysics.collision.CollisionResult:
        ...
    def getMassLowerLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getMassMatrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getMassUpperLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getMasses(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getName(self) -> str:
        ...
    def getNumBodyNodes(self) -> int:
        ...
    def getNumDofs(self) -> int:
        ...
    def getNumSimpleFrames(self) -> int:
        ...
    def getNumSkeletons(self) -> int:
        ...
    def getParallelVelocityAndPositionUpdates(self) -> bool:
        ...
    def getPenetrationCorrectionEnabled(self) -> bool:
        ...
    def getPositionLowerLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getPositionUpperLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getPositions(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getSimFrames(self) -> int:
        ...
    @typing.overload
    def getSimpleFrame(self, index: typing.SupportsInt | typing.SupportsIndex) -> _nimblephysics.dynamics.SimpleFrame:
        ...
    @typing.overload
    def getSimpleFrame(self, name: str) -> _nimblephysics.dynamics.SimpleFrame:
        ...
    @typing.overload
    def getSkeleton(self, index: typing.SupportsInt | typing.SupportsIndex) -> _nimblephysics.dynamics.Skeleton:
        ...
    @typing.overload
    def getSkeleton(self, name: str) -> _nimblephysics.dynamics.Skeleton:
        ...
    def getState(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getStateJacobian(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def getStateSize(self) -> int:
        ...
    def getTime(self) -> float:
        ...
    def getTimeStep(self) -> float:
        ...
    def getUseFDOverride(self) -> bool:
        ...
    def getVelocities(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getVelocityLowerLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getVelocityUpperLimits(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def getWrtMass(self) -> _nimblephysics.neural.WithRespectToMass:
        ...
    def hasSkeleton(self, skeleton: _nimblephysics.dynamics.Skeleton) -> bool:
        ...
    def integratePositions(self, initialVelocity: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def integrateVelocitiesFromImpulses(self, resetCommand: bool = True) -> None:
        ...
    def loadSkeleton(self, path: str, basePosition: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"] = ..., baseEulerAnglesXYZ: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"] = ...) -> _nimblephysics.dynamics.Skeleton:
        ...
    def positionsToJson(self) -> str:
        ...
    def removeAllSimpleFrames(self) -> set[_nimblephysics.dynamics.SimpleFrame]:
        ...
    def removeAllSkeletons(self) -> set[_nimblephysics.dynamics.Skeleton]:
        ...
    def removeDofFromActionSpace(self, dofIndex: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def removeSimpleFrame(self, frame: _nimblephysics.dynamics.SimpleFrame) -> None:
        ...
    def removeSkeleton(self, skeleton: _nimblephysics.dynamics.Skeleton) -> None:
        ...
    def replaceConstraintEngineFn(self, arg0: collections.abc.Callable[[bool], None]) -> None:
        ...
    def reset(self) -> None:
        ...
    def runConstraintEngine(self, arg0: bool) -> None:
        ...
    def runLcpConstraintEngine(self, arg0: bool) -> None:
        ...
    def setAction(self, action: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def setActionSpace(self, actionSpaceMapping: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def setCachedLCPSolution(self, cachedLCPSolution: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def setControlForces(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setControlForcesLowerLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setControlForcesUpperLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setFallbackConstraintForceMixingConstant(self, constant: typing.SupportsFloat | typing.SupportsIndex = 0.001) -> None:
        ...
    def setGravity(self, gravity: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> None:
        ...
    def setMasses(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setName(self, newName: str) -> str:
        ...
    def setParallelVelocityAndPositionUpdates(self, enabled: bool) -> None:
        ...
    def setPenetrationCorrectionEnabled(self, enabled: bool) -> None:
        ...
    def setPositionLowerLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setPositionUpperLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setPositions(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    @typing.overload
    def setSlowDebugResultsAgainstFD(self, setSlowDebugResultsAgainstFD: bool) -> None:
        ...
    @typing.overload
    def setSlowDebugResultsAgainstFD(self, arg0: bool) -> None:
        ...
    def setState(self, state: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def setTime(self, time: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def setTimeStep(self, timeStep: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def setUseFDOverride(self, useFDOverride: bool) -> None:
        ...
    def setVelocities(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setVelocityLowerLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    def setVelocityUpperLimits(self, arg0: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
    @typing.overload
    def step(self) -> None:
        ...
    @typing.overload
    def step(self, resetCommand: bool) -> None:
        ...
    def toJson(self) -> str:
        ...
    def tuneMass(self, arg0: _nimblephysics.dynamics.BodyNode, arg1: _nimblephysics.neural.WrtMassBodyNodeEntryType, arg2: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], arg3: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> None:
        ...
